### ISSUE TITLE
Contributors/Contact: point to same section in se-edu

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level1#83]
The sections in concern can point to the same sections in se-edu, rather than duplicate here.
Make sure all the names here are listed in se-edu page as well.

**Comment by limmlingg** [comment]
We can add Jeffry Hartanto to the list of Contributors in https://se-edu.github.io/docs/Team.html.
Do we need to specify how they contributed? e.g. `Main developer for the first version of the AddressBook-level1` for Leow Yijin.

**Comment by damithc** [comment]
> Do we need to specify how they contributed? e.g. Main developer for the first version of the AddressBook-level1 for Leow Yijin.

Yes, it's good to have some description.
