### ISSUE TITLE
runtests.sh proceeds on compilation error

### ISSUE THREAD

**Issue by hwkchia** [se-edu/addressbook-level1#92]
Exit status of javac not checked. Script continues to run even if javac fails.
This is the same behaviour for runtests.bat.

**Comment by Zhiyuan-Amos** [comment]
@vivekscl intd on this issue? ^^ Since you presented on Bash recently.

**Comment by eugenepeh** [comment]
to verify that it works, can probably try to modify the system environment variable `PATH` a bit to make java doesn't work :P

**Comment by hwkchia** [comment]
Or may I suggest testing the exit status of javac?  If non-zero, then terminate the script prematurely?

**Comment by eugenepeh** [comment]
> Or may I suggest testing the exit status of javac? If non-zero, then terminate the script prematurely?

Yup, sorry for my bad english when I type on the go.
What I actually mean is the fix (testing the exit status of javac) should work when jdk isn't available as well.

**Comment by vivekscl** [comment]
I'll work on this soon, thanks for letting me know @Zhiyuan-Amos!
